#!/usr/bin/env python3
"""Generate NetRadiant .def files from OpenMoHAA QUAKED comments."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


QUAKED_COMMENT = re.compile(r"/\*QUAKED\b.*?\*/", re.DOTALL)
MISSING_COLOR_SPACE = re.compile(r"(/\*QUAKED\s+)([^\s(]+)\(")
CLASSNAME = re.compile(r"/\*QUAKED\s+([^\s(]+)")
OUTPUTS = (
    Path("mohaa.game/main/entities.def"),
    Path("mohaas.game/mainta/entities.def"),
    Path("mohaab.game/maintt/entities.def"),
)
OBSOLETE_G_CLIENT_ENTITIES = {
    "info_player_deathmatch",
    "info_player_intermission",
    "info_player_start",
}


def source_commit(openmohaa: Path) -> str:
    return subprocess.check_output(
        [
            "git",
            "-c",
            f"safe.directory={openmohaa}",
            "-C",
            str(openmohaa),
            "rev-parse",
            "HEAD",
        ],
        text=True,
    ).strip()


def extract_entities(source_dir: Path) -> list[tuple[str, str, str]]:
    entities: list[tuple[str, str, str]] = []

    for source in sorted(source_dir.glob("*.cpp"), key=lambda path: path.name.casefold()):
        text = source.read_text(encoding="utf-8", errors="replace")
        for match in QUAKED_COMMENT.finditer(text):
            comment = MISSING_COLOR_SPACE.sub(r"\1\2 (", match.group(), count=1)
            comment = "\n".join(line.rstrip() for line in comment.splitlines())
            classname_match = CLASSNAME.match(comment)
            if classname_match is None:
                raise RuntimeError(f"Could not parse a classname in {source}")
            classname = classname_match.group(1)
            # These are obsolete Quake 3 duplicates of the richer OpenMoHAA
            # definitions in playerstart.cpp.
            if (
                source.name == "g_client.cpp"
                and classname in OBSOLETE_G_CLIENT_ENTITIES
            ):
                continue
            entities.append((classname, source.name, comment.rstrip()))

    duplicates: dict[str, list[str]] = {}
    for classname, filename, _ in entities:
        duplicates.setdefault(classname, []).append(filename)
    duplicates = {name: files for name, files in duplicates.items() if len(files) > 1}
    if duplicates:
        details = ", ".join(f"{name}: {files}" for name, files in duplicates.items())
        raise RuntimeError(f"Duplicate entity definitions: {details}")

    return sorted(entities, key=lambda item: item[0].casefold())


def render(commit: str, entities: list[tuple[str, str, str]]) -> str:
    header = f"""/*
Generated from OpenMoHAA code/fgame entity documentation.
Source commit: {commit}
Source license: GNU General Public License version 2
Generator: contrib/gamepacks/MOHAApack/tools/generate_entities.py

Do not edit this file directly. Regenerate it from an OpenMoHAA checkout.
*/
"""
    body = "\n\n".join(
        f"// OpenMoHAA source: code/fgame/{filename}\n{comment}"
        for _, filename, comment in entities
    )
    return f"{header}\n{body}\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("openmohaa", type=Path, help="path to an OpenMoHAA checkout")
    args = parser.parse_args()

    openmohaa = args.openmohaa.resolve()
    source_dir = openmohaa / "code" / "fgame"
    if not source_dir.is_dir():
        parser.error(f"{source_dir} is not an OpenMoHAA game-source directory")

    output_root = Path(__file__).resolve().parents[1]
    entities = extract_entities(source_dir)
    if not entities:
        raise RuntimeError("No OpenMoHAA entity definitions were found")

    content = render(source_commit(openmohaa), entities)
    for relative_output in OUTPUTS:
        output = output_root / relative_output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {output} ({len(entities)} entities)")


if __name__ == "__main__":
    main()
